---
- name: Set environment variables
  set_fact:
    PRODUCTION: "!0"
    BASE_URL: "{{ base_url | default('http://192.168.99.16:8080') }}"
    BACKEND_URL: "test"
    REDIRECT_URL: "test"
    HOS_BACKEND_URL: "test"
    ALERT_BACKEND_URL: "test"
    MARKETING_URL: "test"
    INSIGHTS_URL: "test"
    GEO_SERVICE: "test"
    HOSQL_URL: "test"
    RCODE: "test"
    ELASTIC_LOGIN: "test"
    ELASTIC_PASSWORD: "test"
    FULL_REDIRECT: "!0"
    FULL_REDIRECT_PATH: "test"
    PARTIAL_REDIRECT_PATH: "test"
    PARTIAL_USER_LIST: "test"
    INSPECTED_CHECK_ENABLED: "!0"
    EXPOSED_PORT: "{{ exposed_port | default('8080') }}"
  tags: cp_compose

- name: Create application directory
  file:
    path: /opt/magic-login
    state: directory
  tags: cp_compose

- name: Upload docker-compose.yml
  template:
    src: templates/docker-compose.yml.j2
    dest: /opt/magic-login/docker-compose.yml
  tags: cp_compose

- name: Install Docker
  apt:
    name: docker.io
    state: present
  tags: initDocker

- name: Ensure Docker service is started and enabled
  systemd:
    name: docker
    state: started
    enabled: yes
  tags: initDocker

- name: Ensure docker-compose is installed
  apt:
    name: docker-compose
    state: present
  tags: initDocker

- name: Run Docker Compose
  command: docker-compose up -d
  args:
    chdir: /opt/magic-login
  tags: buildImage