---
- name: Create application directory
  file:
    path: /opt/magic-login
    state: directory
  tags: cp_compose

- name: Upload docker-compose.yml
  template:
    src: templates/docker-compose.yml.j2
    dest: /opt/magic-login/docker-compose.yml
  tags: cp_compose

- name: Install Docker
  apt:
    name: docker.io
    state: present
  tags: initDocker

- name: Ensure Docker service is started and enabled
  systemd:
    name: docker
    state: started
    enabled: yes
  tags: initDocker

- name: Ensure docker-compose is installed
  apt:
    name: docker-compose
    state: present
  tags: initDocker

- name: Run Docker Compose
  command: docker-compose up -d
  args:
    chdir: /opt/magic-login
  tags: buildImage

# - name: cptest
#   copy:
#     src: files/docker-compose.yml
#     dest: /opt/magic-login/docker-compose.yml
#   tags: cptest