# This is the network config written by 'subiquity'
network:
  version: 2
  ethernets:
    ens18:
      dhcp4: false
      dhcp6: false
      addresses:
      - 192.168.99.18/24
      gateway4: 192.168.99.1
      nameservers:
       addresses: [8.8.8.8,8.8.8.4]